# Generated by Django 5.2.16 on 2026-07-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
