# Generated by Django 5.2.16 on 2026-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analysisjob_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
