# Generated by Django 5.2.16 on 2026-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_alter_analysisjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('cloning', 'Cloning'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning'), ('processing', 'Processing'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
